version: '3.9'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    environment: 
      - ENVIRONMENT=production
    ports:
      - 8000:8000
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:13
    shm_size: 1g
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database1
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: