version: '3.9'

services:
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    environment: 
      - ENVIRONMENT=production
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    # links:
    #   # - redis
    # depends_on:
    #   # - redis

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  # redis:
  #   image: redis
  #   command: "redis-server"
  #   ports:
  #     - "14000:6379"
  #   volumes:
  #     - redis_data:/data