version: '3.9'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    build: ./config/nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
    # links:
    #   # - redis
    # depends_on:
    #   # - redis
 
  # redis:
  #   image: redis
  #   command: "redis-server"
  #   ports:
  #     - "14000:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  static_volume: