version: '3.9'

services:
  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    shm_size: 1g
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database1
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    command: "redis-server"
    ports:
      - "14000:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:

