version: '3.9'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/HealthTrace/staticfiles
    expose:
      - 8000
    env_file:
      - .env
 
  # redis:
  #   image: redis
  #   command: "redis-server"
  #   ports:
  #     - "14000:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  static_volume:
