version: '3.9'

services:
  web:
    build: .
    command: gunicorn server.wsgi -b 0.0.0.0:8000
    environment: 
      - ENVIRONMENT=development
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    links:
      - db
      # - redis
    depends_on:
      - db
      # - redis
  db:
    image: postgres:13
    shm_size: 1g
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database1
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  # redis:
  #   image: redis
  #   command: "redis-server"
  #   ports:
  #     - "14000:6379"
  #   volumes:
  #     - redis_data:/data
volumes:
  postgres_data:
  # redis_data:


    #AWS CREDS
    # DB USER: abeelcf
    # DB PASS: ncDl57PIWiaG41B9mWm1
    # docker run -it --rm postgres psql --host healthcare-db-1.cs6wxy3pcyxd.us-east-1.rds.amazonaws.com --port 5432 --username abeelcf --dbname postgres
