# Generated by Django 3.2.8 on 2021-10-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0004_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='StreetAddress1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='StreetAddress2',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
