# Generated by Django 3.2.8 on 2021-10-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0005_auto_20211022_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='PrimaryType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Contextual_Info',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Nature_Payment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
