# Generated by Django 3.2.8 on 2021-10-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0006_auto_20211022_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manafacturer',
            name='ManafacturerId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
