# Generated by Django 3.2.8 on 2021-10-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0008_auto_20211023_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Manafacturer',
            new_name='Manufacturer',
        ),
    ]
