# Generated by Django 3.2.8 on 2021-10-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0009_rename_manafacturer_transaction_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='PrimaryType',
        ),
    ]
