# Generated by Django 3.2.8 on 2021-10-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0010_remove_doctor_primarytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['Date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Category',
            new_name='Category_1',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Name',
            new_name='Name_1',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Type_Product',
            new_name='Type_Product_1',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Category_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Category_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Category_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Category_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Name_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Name_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Name_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Name_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Type_Product_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Type_Product_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Type_Product_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Type_Product_5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
