# Generated by Django 3.2.8 on 2021-10-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0011_auto_20211025_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Name_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Name_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Name_3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Name_4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Name_5',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Pay_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
