# Generated by Django 3.2.8 on 2021-10-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0012_auto_20211025_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='TotalPay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='TotalPayments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
    ]
