# Generated by Django 3.2.8 on 2021-10-26 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0013_auto_20211026_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='TotalPay',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='TotalPayments',
        ),
    ]
