# Generated by Django 3.2.8 on 2021-10-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0016_auto_20211026_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Product', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
