# Generated by Django 3.2.8 on 2021-10-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0018_transaction_transactionitems'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['Type_Product', 'Category', 'Name'], name='healthdata__Type_Pr_3b3da5_idx'),
        ),
    ]
