# Generated by Django 3.2.8 on 2021-10-30 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0019_transactionitem_healthdata__type_pr_3b3da5_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Category_1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Category_2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Category_3',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Category_4',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Category_5',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Name_1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Name_2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Name_3',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Name_4',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Name_5',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Type_Product_1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Type_Product_2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Type_Product_3',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Type_Product_4',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Type_Product_5',
        ),
    ]
