# Generated by Django 3.2.8 on 2021-10-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0020_auto_20211030_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-Pay_Amount']},
        ),
    ]
