# Generated by Django 3.2.8 on 2021-10-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0021_alter_transaction_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['DoctorId'], name='healthdata__DoctorI_881c39_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['TransactionId'], name='healthdata__Transac_c92e14_idx'),
        ),
    ]
