# Generated by Django 3.2.8 on 2021-10-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0022_auto_20211031_1855'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctor',
            name='healthdata__DoctorI_881c39_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='healthdata__Transac_c92e14_idx',
        ),
        migrations.RemoveIndex(
            model_name='transactionitem',
            name='healthdata__Type_Pr_3b3da5_idx',
        ),
    ]
