# Generated by Django 3.2.8 on 2021-11-02 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0024_transaction_healthdata__doctor__8c53ab_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-Date']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturerTransactions', to='healthdata.manufacturer'),
        ),
    ]
