# Generated by Django 3.2.9 on 2021-11-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0026_transaction_healthdata__manufac_4fa552_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['TransactionId'], name='healthdata__Transac_c92e14_idx'),
        ),
    ]
