# Generated by Django 3.2.9 on 2021-11-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0027_transaction_healthdata__transac_c92e14_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionitems',
            field=models.ManyToManyField(related_name='In_Transaction', to='healthdata.TransactionItem'),
        ),
    ]
