# Generated by Django 3.2.9 on 2021-11-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0028_alter_transaction_transactionitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionitems',
            field=models.ManyToManyField(to='healthdata.TransactionItem'),
        ),
    ]
