# Generated by Django 3.2.9 on 2021-11-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0030_alter_transaction_transactionitems'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['id'], name='healthdata__id_89b63d_idx'),
        ),
    ]
