# Generated by Django 3.2.9 on 2021-11-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0031_transactionitem_healthdata__id_89b63d_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionitem',
            name='healthdata__id_89b63d_idx',
        ),
    ]
