# Generated by Django 3.2.9 on 2021-11-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0032_remove_transactionitem_healthdata__id_89b63d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='SummaryData',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
