# Generated by Django 3.2.9 on 2021-11-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0033_manufacturer_summarydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='Opiod',
            field=models.BooleanField(default=False),
        ),
    ]
