# Generated by Django 3.2.9 on 2021-11-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0034_transactionitem_opiod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='Opiod',
            new_name='Opioid',
        ),
    ]
