# Generated by Django 3.2.9 on 2021-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0036_alter_transactionitem_opioid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='OpioidInvolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
