# Generated by Django 3.2.9 on 2021-11-14 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0037_transaction_opioidinvolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='healthdata.doctor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturerTransactions', to='healthdata.manufacturer'),
        ),
    ]
