# Generated by Django 3.2.9 on 2021-11-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0038_auto_20211114_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['LastName', 'FirstName']},
        ),
    ]
