# Generated by Django 3.2.9 on 2021-11-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0040_doctor_healthdata__firstna_520de1_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctor',
            name='healthdata__FirstNa_520de1_idx',
        ),
    ]
