# Generated by Django 3.2.9 on 2021-11-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0041_remove_doctor_healthdata__firstna_520de1_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['FirstName', 'LastName'], name='healthdata__FirstNa_520de1_idx'),
        ),
    ]
