# Generated by Django 3.2.9 on 2021-11-27 19:04

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0042_doctor_healthdata__firstna_520de1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('SummaryData', models.JSONField(blank=True, null=True)),
                ('MapData', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_name_idx',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
