# Generated by Django 3.2.9 on 2021-11-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0046_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('map', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
