# Generated by Django 3.2.9 on 2021-11-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0047_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='transformation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
