# Generated by Django 3.2.9 on 2021-11-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0048_state_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='twolettercode',
            field=models.CharField(default='NA', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
