# Generated by Django 3.2.9 on 2021-12-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0049_auto_20211128_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='ranking',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
